/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function list_providers(): Array<string>
export declare function generate_response(prompt: string): Promise<string>
