/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function listProviders(): Array<string>
export interface MessageInput {
  role: string
  content: string
}
export declare function chat(messages: Array<MessageInput>): Promise<string>
